#!/bin/sh

# Start all init scripts in init.d
# executing them in numerical order.
#
for i in /usr/local/etc/init.d/S??* ;do

 # Ignore dangling symlinks (if any).
 [ ! -f "$i" ] && continue

 case "$i" in
   *.sh)
     # Source shell script for speed.
     (
       trap - INT QUIT TSTP
       set start
       . $i
     )
     ;;
   *)
     # No sh extension, so fork subprocess.
     $i start
     ;;
  esac
done
